import { IndustryPack } from "./types";

/**
 * The first complete Industry Knowledge Pack. Six real categories,
 * chosen to cover the sprint's own 10 test variants without inventing
 * categories no real test case needs: Laptops, Gaming PCs, Premium/Apple
 * Reseller, IT & Business Equipment, Computer Accessories, and General
 * Electronics Retail (the catch-all for phrasing too generic to place in
 * a more specific category — itself a real, honest category, not a
 * fabricated one).
 */
export const CONSUMER_ELECTRONICS_PACK: IndustryPack = {
  id: "pack-consumer-electronics",
  industry: "Consumer Electronics",
  source: "Smarkin Industry Pack v1",
  confidence: 85,
  version: "1.0.0",
  lastUpdated: "2026-07-21",

  categories: [
    {
      category: "Laptops", subcategory: null,
      products: ["Laptop", "Notebook", "Ultrabook", "Refurbished laptop", "Used laptop"],
      services: ["Laptop repair", "Trade-in", "Warranty service"],
      businessModel: "Retail (new and/or refurbished hardware resale)",
      revenueModel: "Per-unit margin on hardware sales, plus repair/warranty service fees",
      classificationRules: {
        aliases: ["laptop store", "laptop shop", "refurbished laptop shop", "used laptop dealer", "used laptop store"],
        keywords: ["laptop", "notebook computer", "ultrabook", "refurbished laptop", "laptop repair"],
        confidenceHint: 90,
      },
    },
    {
      category: "Gaming PCs", subcategory: null,
      products: ["Gaming desktop", "Gaming laptop", "Graphics card", "Gaming peripherals"],
      services: ["Custom PC building", "Overclocking service", "PC repair"],
      businessModel: "Retail and custom-build assembly",
      revenueModel: "Hardware margin plus build/assembly service fees",
      classificationRules: {
        aliases: ["gaming pc store", "gaming computer store", "custom pc builder"],
        keywords: ["gaming pc", "gaming desktop", "graphics card", "custom build", "gaming rig"],
        confidenceHint: 90,
      },
    },
    {
      category: "Premium & Reseller", subcategory: "Apple Reseller",
      products: ["MacBook", "iMac", "iPad", "Apple accessories"],
      services: ["AppleCare enrollment", "Device trade-in", "Repair services"],
      businessModel: "Authorized or independent resale of premium branded hardware",
      revenueModel: "Hardware margin, typically thinner than generic retail due to brand pricing control",
      classificationRules: {
        aliases: ["apple reseller", "apple authorized reseller", "mac store"],
        keywords: ["macbook", "apple products", "imac", "ipad reseller"],
        confidenceHint: 88,
      },
    },
    {
      category: "IT & Business Equipment", subcategory: null,
      products: ["Business laptop", "Desktop workstation", "Office computer", "Networking equipment"],
      services: ["Bulk procurement", "IT equipment leasing", "On-site support contracts"],
      businessModel: "B2B hardware supply, often with recurring service/support contracts",
      revenueModel: "Bulk-order hardware margin plus recurring support/leasing revenue",
      classificationRules: {
        aliases: ["it equipment supplier", "office computer store", "business it supplier"],
        keywords: ["it equipment", "office computers", "business workstations", "networking equipment", "bulk computer supply"],
        confidenceHint: 88,
      },
    },
    {
      category: "Computer Accessories", subcategory: null,
      products: ["Mouse", "Keyboard", "Monitor", "Webcam", "Laptop bag", "Charger"],
      services: ["Accessory bundling", "Same-day delivery"],
      businessModel: "High-volume, low-margin accessory retail",
      revenueModel: "Per-unit margin across a large product catalog, reliant on volume",
      classificationRules: {
        aliases: ["computer accessories shop", "computer accessories store", "pc accessories shop"],
        keywords: ["computer accessories", "laptop accessories", "keyboard and mouse", "monitor and webcam"],
        confidenceHint: 88,
      },
    },
    {
      category: "General Electronics Retail", subcategory: null,
      products: ["Computers", "Laptops", "Phones", "General electronics"],
      services: ["Repair", "Trade-in", "Warranty"],
      businessModel: "General consumer electronics retail across multiple product lines",
      revenueModel: "Hardware margin across a broad, mixed catalog",
      classificationRules: {
        aliases: ["electronics shop", "electronics store", "computer retailer", "computer store"],
        keywords: ["consumer electronics", "computer retail", "electronics retail"],
        confidenceHint: 75,
      },
    },
  ],

  industryIntelligence: {
    marketOverview: "Consumer electronics retail spans new-hardware sales, refurbished/used resale, and B2B equipment supply, with margins varying sharply by segment — thin on premium branded hardware, thicker on accessories and refurbished units.",
    typicalCompetitors: ["Large electronics retail chains", "Online marketplaces", "Direct-from-manufacturer sales", "Other local independent retailers"],
    customerExpectations: ["Genuine/verified hardware condition", "Working warranty coverage", "Competitive pricing versus large chains", "Knowledgeable staff for technical questions"],
    buyingCycle: "Short for accessories (same-day/impulse), moderate for laptops/desktops (days to weeks of comparison shopping), longer for bulk B2B equipment (formal procurement cycles)",
    pricingModels: ["Fixed retail pricing", "Bulk/volume B2B pricing", "Trade-in credit pricing", "Financing/installment plans"],
    seasonality: "Back-to-school (Aug-Sep) and holiday season (Nov-Dec) are real, well-documented peaks for consumer electronics retail broadly",
    regulations: null,
    marketTrends: ["Growing refurbished/used hardware market", "Remote-work-driven demand for home office equipment", "Rising graphics card prices affecting gaming PC margins"],
    businessRisks: ["Thin margins on premium brands", "Rapid hardware depreciation", "Counterfeit/grey-market component risk in accessories"],
    opportunities: ["Refurbished hardware as a lower-price-point entry", "B2B recurring support contracts as stable revenue", "Trade-in programs building repeat customer relationships"],
  },

  personas: [
    {
      personaName: "Budget-Conscious Student", category: "Laptops",
      description: "A student needing a reliable laptop for coursework on a tight budget.",
      goals: ["Get a laptop that lasts through a degree program", "Stay within a strict budget"],
      painPoints: ["New laptops are too expensive", "Uncertain if a refurbished unit will actually last"],
      frustrations: ["Confusing warranty terms on used hardware", "Pressure to buy features they don't need"],
      buyingMotivations: ["Price", "Portability", "Battery life for all-day classes"],
      objections: ["Worried a refurbished laptop will fail quickly", "Unsure about the real condition of used hardware"],
      decisionCriteria: ["Price", "Battery life", "Verified condition/warranty"],
      emotionalDrivers: ["Avoiding regret over a bad purchase decision", "Financial stress relief"],
      preferredCommunication: ["Instagram", "TikTok", "Student-forum word of mouth"],
      customerJourney: "Compares prices across multiple sellers, reads reviews on refurbished condition, decides close to semester start",
      typicalBudget: "$300-$700",
    },
    {
      personaName: "PC Gaming Enthusiast", category: "Gaming PCs",
      description: "A gamer wanting maximum performance for a specific budget, often building or upgrading rather than buying prebuilt.",
      goals: ["Maximize frame rate and performance per dollar", "Future-proof the build for upcoming games"],
      painPoints: ["Graphics card prices are volatile and often inflated", "Hard to trust prebuilt PC component quality"],
      frustrations: ["Marketing hype not matching real benchmark performance", "Bottlenecked components sold as balanced builds"],
      buyingMotivations: ["Raw performance", "Upgradability", "Brand reputation of components"],
      objections: ["Worried prebuilt PCs use lower-quality components to hit a price point", "Skeptical of advertised performance claims"],
      decisionCriteria: ["Benchmark performance", "Component brand reputation", "Upgrade path"],
      emotionalDrivers: ["Pride in a well-built rig", "Competitive gaming performance"],
      preferredCommunication: ["YouTube", "Reddit", "Discord communities"],
      customerJourney: "Extensive research phase comparing benchmarks, price-tracks components before buying, often waits for sales",
      typicalBudget: "$1,000-$3,000",
    },
    {
      personaName: "Brand-Loyal Professional", category: "Premium & Reseller",
      description: "A professional who specifically wants Apple hardware for ecosystem integration and reliability.",
      goals: ["Seamless integration with existing Apple devices", "Long-term device reliability"],
      painPoints: ["Premium pricing strains budget", "Concerned about counterfeit accessories from unauthorized sellers"],
      frustrations: ["Unclear whether a reseller is genuinely authorized", "Long repair wait times"],
      buyingMotivations: ["Ecosystem integration", "Brand reliability", "Resale value retention"],
      objections: ["Worried about authenticity when buying from a reseller rather than Apple directly", "Price premium versus equivalent specs elsewhere"],
      decisionCriteria: ["Verified authorized reseller status", "AppleCare availability", "Trade-in value"],
      emotionalDrivers: ["Trust in brand reliability", "Status association"],
      preferredCommunication: ["Email", "In-person consultation"],
      customerJourney: "Researches authorized reseller status first, then compares trade-in offers, purchases with AppleCare",
      typicalBudget: "$1,000-$2,500",
    },
    {
      personaName: "IT Procurement Manager", category: "IT & Business Equipment",
      description: "A business buyer responsible for equipping an office with reliable, supportable hardware at scale.",
      goals: ["Equip staff reliably without downtime", "Negotiate favorable bulk pricing and support terms"],
      painPoints: ["Hardware failures cause real productivity loss", "Justifying IT spend to leadership"],
      frustrations: ["Vendors that can't reliably fulfill bulk orders on schedule", "Inconsistent support response times"],
      buyingMotivations: ["Reliability at scale", "Support contract quality", "Total cost of ownership"],
      objections: ["Worried about vendor reliability for large orders", "Uncertain about total cost including support"],
      decisionCriteria: ["Bulk pricing", "Support contract terms", "Delivery reliability"],
      emotionalDrivers: ["Avoiding blame for IT failures", "Being seen as a competent decision-maker"],
      preferredCommunication: ["Email", "Direct sales calls", "LinkedIn"],
      customerJourney: "Formal RFP/quote comparison process, references checked, contract negotiated before purchase",
      typicalBudget: "$10,000+ per order",
    },
    {
      personaName: "Practical Accessory Shopper", category: "Computer Accessories",
      description: "A shopper making a quick, practical purchase to solve an immediate need.",
      goals: ["Solve an immediate need (broken mouse, new monitor) quickly"],
      painPoints: ["Broken/lost accessory disrupting daily work", "Too many near-identical options to choose from"],
      frustrations: ["Decision fatigue from excessive product choice", "Slow shipping when the need is urgent"],
      buyingMotivations: ["Convenience", "Speed of fulfillment", "Price"],
      objections: ["Unsure which option is actually reliable versus cheaply made"],
      decisionCriteria: ["Price", "Reviews", "Delivery speed"],
      emotionalDrivers: ["Relief from an immediate disruption"],
      preferredCommunication: ["Search/Google", "Marketplace reviews"],
      customerJourney: "Short, need-driven purchase, minimal comparison shopping, same-day or next-day decision",
      typicalBudget: "$15-$150",
    },
  ],

  audienceKnowledge: {
    interests: ["Technology", "Gaming", "Computer hardware", "Productivity software", "Consumer electronics"],
    behaviors: ["Online tech reviews readers", "Comparison shoppers", "Early technology adopters"],
    demographics: ["18-24 (students)", "25-40 (professionals)", "35-55 (IT/business buyers)"],
    occupations: ["Student", "Software professional", "IT manager", "Gamer/content creator", "Office administrator"],
    education: ["High school", "Some college", "Bachelor's degree"],
    incomeRanges: ["$20,000-$40,000 (students)", "$50,000-$90,000 (professionals)", "Business budget (B2B buyers)"],
    deviceUsage: ["Primary laptop/desktop user", "Multi-device users researching on mobile before buying on desktop"],
    platformPreferences: ["YouTube", "Reddit", "Google Search", "Instagram (accessories/lifestyle)"],
    purchaseIntent: "High for replacement/upgrade purchases triggered by a specific failure or need; moderate-to-long consideration cycle for new purchases",
    audienceSignals: ["Searches for product comparisons", "Visits multiple retailer sites before buying", "Reads/watches benchmark and review content"],
    geographicPatterns: ["Urban and suburban concentration for retail foot traffic", "Broader geographic reach for online/B2B sales"],
    channelSuitability: [
      { platform: "Google Ads", suitability: 80 },
      { platform: "Meta Ads", suitability: 60 },
      { platform: "YouTube", suitability: 65 },
      { platform: "LinkedIn", suitability: 55 },
    ],
  },

  marketingKnowledge: {
    positioningIdeas: ["The trusted local alternative to big-box electronics chains", "Verified, warrantied refurbished hardware you can trust", "Bulk IT equipment with support that actually responds"],
    valuePropositions: ["Save money without sacrificing reliability", "Get expert guidance a big chain won't give you", "One vendor for hardware and ongoing support"],
    messagingAngles: ["Verified condition, not just 'refurbished'", "Built for your specific use case, not one-size-fits-all", "Local support when something goes wrong"],
    hooks: ["Still paying full price for last year's laptop?", "Your gaming PC is only as good as its weakest component", "Stop waiting days for IT support that never shows up"],
    headlines: ["Verified Refurbished Laptops, Real Warranty Included", "Custom Gaming PCs Built for Your Budget", "Bulk IT Equipment With Support That Actually Responds"],
    offers: ["Free diagnostic with any repair", "Trade-in credit toward a new purchase", "Bulk order discount for 10+ units"],
    riskReducers: ["30-day return policy", "Verified condition report on every refurbished unit", "On-site support included with bulk orders"],
    trustBuilders: ["Authorized reseller certification", "Visible customer reviews with photos", "Transparent condition grading system"],
    callsToAction: ["Get a free quote", "See verified condition report", "Book a repair diagnostic"],
    creativeThemes: ["Before/after refurbishment transformation", "Real benchmark performance comparisons", "Behind-the-scenes of the repair/build process"],
    campaignObjectives: ["Drive in-store/online purchase for new customers", "Retarget past customers for upgrade/trade-in", "Generate B2B quote requests"],
    funnelIdeas: ["Cold traffic to a comparison/buying-guide content piece, retarget with a specific offer", "B2B: gated pricing sheet download to capture leads for direct sales follow-up"],
  },
};
